import Head from "next/head";
import Main from "../components/Main/Main";
import Layout from "../components/Layout/Layout";
import firebase from "../firebase/initFirebase";
export default function Home(props) {
  return (
    <Layout>
      <div className="w-full flex justify-center mt-24 px-5 lg:py-5 lg:pl-0 lg:pr-10">
        <Head>
          <title> YouTube </title>{" "}
          <meta
            name="YouTube Clone by Nextjs, Tailwincss, and Firebase"
            content="Generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>{" "}
        <main className="w-full">
          {" "}
          <Main data={props.data} />{" "}
        </main>{" "}
      </div>{" "}
    </Layout>
  );
}

export async function getServerSideProps() {
  function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      // console.log(j);
      var temp = array[i];
      array[i] = array[j];
      array[j] = temp;
    }
  }
  const dataArr = [];
  const res = await firebase.firestore().collection("videos").get();
  const data = res.docs;
  data.map((value) => dataArr.push(value.data()));
  shuffleArray(dataArr);
  return {
    props: {
      data: dataArr,
    },
  };
}
